# Generated by Django 5.1.3 on 2026-04-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('po_complete', 'PO Complete'), ('po_partial', 'PO Partial'), ('po_cancel', 'PO Cancelled'), ('adjustment', 'Manual Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('sale', 'Sale'), ('return', 'Return')], max_length=100),
        ),
    ]
