# Generated by Django 5.1.3 on 2025-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='polineitem',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0, help_text='The amount that has actually arrived in the warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partial', 'Partially Received'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
