# Generated by Django 5.1.3 on 2026-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_polineitem_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='polineitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount that has actually arrived in the warehouse', max_digits=12),
        ),
    ]
